### ISSUE TITLE
Metadata in package.xml is being ignored and overwritten when Editing Project

### ISSUE THREAD

**Issue by abd3** [joeferraro/MavensMate#546]
The metadata in our project includes EmailTemplates and Layouts, and there are many specific entries for those in our package.xml file. When we go to Edit Project in Mavensmate our other metadata is listed, but the EmailTemplates and Layouts are de-selected. If we actually click "Update Project", all of the EmailTemplates and Layout files are removed from our project and those entries are deleted from package.xml. This issue is new for us since moving to the MM app from MM-SublimeText 4.0.5.
<img width="276" alt="screen shot 2015-10-01 at 11 00 43" src="https://cloud.githubusercontent.com/assets/11654102/10224399/b4e2a034-682b-11e5-842b-d60d837b8fd6.png">

I'm on OS X, using Sublime Text MM v 5.0.0, and the MM App v0.0.6

**Comment by joeferraro** [comment]
would you mind setting up logging in mavensmate-app (in settings) and pasting any relevant logs?

**Comment by joeferraro** [comment]
what platform is this?

**Comment by abd3** [comment]
Thanks for your fast response. I cleared my logs (set to Debug level) and then logged as I clicked "Edit Project", it read in my package.xml, and then when I clicked "Update Project", it removed the email templates and layouts from my project.
Logs are here: https://gist.github.com/abd3/2a417c6c6f45aec7b5da

**Comment by abd3** [comment]
From my own naive view of the logs, lines 20 + 22 seem to indicate that the package.xml was parsed correctly; line 87-88 seems to indicate that this metadata was requested from Salesforce; line 99 seems to indicate that some of the EmailTemplates and Layouts have "checked=true" set.

But lines 100-101 seem like they're missing the EmailTemplates and Layouts:
2015-10-01T15:13:57.583Z - debug: Processing request POST for URL: /app/project/update?pid=HFX4PHS9R2MSDS434W1CNWBFUDNSPW9R
2015-10-01T15:13:57.583Z - debug: post body ...

**Comment by joeferraro** [comment]
Thanks, this helped me uncover/patch a bug with Layouts.

Im guessing you have all EmailTemplates checked?

**Comment by abd3** [comment]
Great, I'm glad that issue was resolved. We're not using all the EmailTemplates. We only have a subset selected. Do you expect that the code fix you made will also fix the EmailTemplates issues?

**Comment by joeferraro** [comment]
we shall see, but that's the intent. thanks

**Comment by joeferraro** [comment]
fix available in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7

**Comment by abd3** [comment]
Hi Joe.
I downloaded and tried v0.0.7 but the bug persists. I've uploaded a shorter log (I just clicked "Edit Project", and didn't actually "Update Project" this time) since the issue is already present on the edit screen. No EmailTemplates or Layouts are selected.
https://gist.github.com/abd3/2a417c6c6f45aec7b5da#file-mm-v0-0-7-just-edit

**Comment by joeferraro** [comment]
@abd3 I'm pretty sure you'll need to refresh your metadata cache. Can you click on the "refresh" icon on the Project Metadata tab and see whether this still persists?

<img width="269" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/10229544/bf412dbe-6846-11e5-81d1-d0d5876d59b3.png">

**Comment by abd3** [comment]
Ba-da-bing!  Thanks, Joe!!! Works now. This fixes a blocking issue for our project team, thanks so much for your Lightning (component) speed.

**Comment by joeferraro** [comment]
@abd3 :+1:
