### ISSUE TITLE
Unable to create project from existing folder from git

### ISSUE THREAD

**Issue by cfajardo-ghi** [joeferraro/MavensMate#758]
* **MavensMate Desktop Version**:v0.0.10

* **Editor**:Sublime 3

* **MavensMate Plugin Version**:7.0.1

* **Platform/Version**:OS X 10.11.1

* **Proxy Details**:no

* **Salesforce API Version**:36.0

* **Salesforce Server**:cs4

1. I downloaded the project from our git repo
2. I drag the downloaded project folder over to Sublime to open
3. In Sublime, I right click and go to MavensMate > Create MavensMate Project...

When the MavensMate desktop app opens, the project directory shows the correct path, but the Project Name field is empty and is read-only.  So if I try entering my Salesforce credentials and create the project, it tells me the error: "Please specify username, password, and project name". But I can't specify the project name.    

This was working the last time I created a project from an existing folder, which was about a month ago. It pre-filled the project name with the name of the project folder.

Below is the snippet of the log (removed username/pwd that was in clear text!). Origin appears empty:
2016-09-22T15:50:14.338Z - debug: executeCommand payload is: {"name":"","username":"*******","password":"*******","orgType":"sandbox","workspace":"/users/cfajardo/code/mavensmate","loginUrl":"","origin":""}
2016-09-22T15:50:14.338Z - debug: command class is: NewProjectFromExistingDirectoryCommand
2016-09-22T15:50:14.340Z - info: handling command result: 
2016-09-22T15:50:14.341Z - error:  Error: Please specify username, password, and project name
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/project/new-project-from-existing-directory.js:37:23
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at Command.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/project/new-project-from-existing-directory.js:25:10)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:423:21
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at Client.executeCommand (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:409:10)
    at ProjectController.createFromExisting (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/ui/controllers/project.js:101:15)
    at UIServer.appRequestHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/ui/server.js:173:28)
    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)
    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)

**Comment by olegkord** [comment]
Experiencing the same issue but with SVN. Please help!!

**Comment by claranice** [comment]
Same.

**Comment by fireredlink5000** [comment]
Same

**Comment by bobteplitsky** [comment]
Same here.  https://github.com/joeferraro/MavensMate/issues/760

**Comment by joeferraro** [comment]
fixed via https://github.com/joeferraro/MavensMate-SublimeText/releases/tag/7.0.2 (should hit package control soon)

**Comment by cfajardo-ghi** [comment]
Thanks @joeferraro for fixing! I tried to upgrade via package control and it still shows there are no packages available for upgrade.  When can we expect it to be available?

**Comment by zen-gary** [comment]
Still having this issue as well, and can't see the upgrade available.

**Comment by plangston** [comment]
any news on this, still hitting this error

**Comment by DavidCDean** [comment]
I also have this issue again. Updated the desktop app to the newest downloadable beta and checked for a plugin update in ST (prereleases enabled). Cannot create a project with existing. It _seems_ to behave much like it has when this problem surfaced in past releases. I can't remember what the work-arounds were, though.

**Comment by bobteplitsky** [comment]
My personal workaround was to move over to using Atom instead of Sublime :)
